#ifndef FORWARD_COMMAND_CONTROLLER__MULTI_INTERFACE_FORWARD_COMMAND_CONTROLLER_HPP_
#define FORWARD_COMMAND_CONTROLLER__MULTI_INTERFACE_FORWARD_COMMAND_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "forward_command_controller/forward_controllers_base.hpp"
#include "forward_command_controller/visibility_control.h"
// auto-generated by generate_parameter_library
#include "forward_command_controller/multi_interface_forward_command_controller_parameters.hpp"

namespace forward_command_controller
{
/**
 * \brief Multi-interface forward command controller for a set of joints.
 *
 * This controller subscribes to JointGroupCommand messages on ~/multi_joint_command
 * and forwards both position and duration commands to the hardware interfaces.
 * Each joint in the group receives its own target position (radians) and
 * execution duration (0-2000ms).
 *
 * \param joints Names of the joints to control.
 * \param interface_names Names of the interfaces to command (e.g., ["position", "duration"]).
 *
 * Subscribes to:
 * - \b ~/multi_joint_command (forward_command_controller_msgs::msg::JointGroupCommand) :
 *   Array of joint commands, each with joint_id, position_rad, and duration_ms.
 */
class MultiInterfaceForwardCommandController : public ForwardControllersBase
{
public:
  FORWARD_COMMAND_CONTROLLER_PUBLIC
  MultiInterfaceForwardCommandController();

  FORWARD_COMMAND_CONTROLLER_PUBLIC
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;

protected:
  void declare_parameters() override;
  controller_interface::CallbackReturn read_parameters() override;

  /** Override update to process JointGroupCommand instead of Float64MultiArray */
  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  std::shared_ptr<multi_interface_forward_command_controller::ParamListener> param_listener_;
  multi_interface_forward_command_controller::Params params_;

  realtime_tools::RealtimeBuffer<std::shared_ptr<JointGroupCmdType>> rt_group_command_ptr_;
  rclcpp::Subscription<JointGroupCmdType>::SharedPtr group_command_subscriber_;
};

}  // namespace forward_command_controller

#endif  // FORWARD_COMMAND_CONTROLLER__MULTI_INTERFACE_FORWARD_COMMAND_CONTROLLER_HPP_
